version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-zelify
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: zelify
      POSTGRES_PASSWORD: zelify
    ports:
      - "5432:5432"
  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka-zelify
    ports:
      - "9092:9092"
    expose:
      - "9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "transactions:1:1"
  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper-zelify
    ports:
      - "2181:2181"